## 다음 영화 사이트
### https://movie.daum.net/ranking/boxoffice/weekly

- 탑건
- #mainContent > div > div.box_boxoffice > ol > li:nth-child(1) > div > div.thumb_cont > strong > a

In [1]:
from bs4 import BeautifulSoup
from urllib.request import urlopen
import pandas as pd

In [2]:
url = "https://movie.daum.net/ranking/boxoffice/weekly"
page = urlopen(url)
soup = BeautifulSoup(page, "html.parser")

In [3]:
li_lists = soup.select("#mainContent > div > div.box_boxoffice > ol > li > div > div.thumb_cont > strong > a")
# soup.select("#mainContent .link_txt") # 짧은 버전
for list in li_lists:
    print(list.string)

탑건: 매버릭
마녀(魔女) Part2. The Other One
범죄도시 2
브로커
버즈 라이트이어
쥬라기 월드: 도미니언
극장판 윌벤져스 : 수상한 캠핑 대소동
극장판 포켓몬스터DP: 기라티나와 하늘의 꽃다발 쉐이미
헤어질 결심
룸 쉐어링
니 부모 얼굴이 보고 싶다
로스트 시티
모어
니얼굴
애프터 양

In [4]:
count = 0
titleLists = [] # 영화 제목 list
countLists = [] # 순위 list

for list in li_lists:
    count += 1
    print(count , list.string.strip())
    countLists.append(count)
    titleLists.append(list.string.strip())

1 탑건: 매버릭
2 마녀(魔女) Part2. The Other One
3 범죄도시 2
4 브로커
5 버즈 라이트이어
6 쥬라기 월드: 도미니언
7 극장판 윌벤져스 : 수상한 캠핑 대소동
8 극장판 포켓몬스터DP: 기라티나와 하늘의 꽃다발 쉐이미
9 헤어질 결심
10 룸 쉐어링
11 니 부모 얼굴이 보고 싶다
12 로스트 시티
13 모어
14 니얼굴
15 애프터 양

In [5]:
print(countLists , titleLists)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] ['탑건: 매버릭', '마녀(魔女) Part2. The Other One', '범죄도시 2', '브로커', '버즈 라이트이어', '쥬라기 월드: 도미니언', '극장판 윌벤져스 : 수상한 캠핑 대소동', '극장판 포켓몬스터DP: 기라티나와 하늘의 꽃다발 쉐이미', '헤어질 결심', '룸 쉐어링', '니 부모 얼굴이 보고 싶다', '로스트 시티', '모어', '니얼굴', '애프터 양']

### 만든 리스트로 데이터 프레임 만들기

In [6]:
# countlist 만으로 data frame 생성
df = pd.DataFrame(data = countLists, columns = [ '순위'])
df

    순위
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9   10
10  11
11  12
12  13
13  14
14  15

In [7]:
# 기존 Dataframe에 컬럼과 Lists 추가
df['영화제목'] = pd.Series(titleLists) # series는 R에서의 벡터 같은 역할
df

    순위                            영화제목
0    1                         탑건: 매버릭
1    2     마녀(魔女) Part2. The Other One
2    3                          범죄도시 2
3    4                             브로커
4    5                        버즈 라이트이어
5    6                    쥬라기 월드: 도미니언
6    7           극장판 윌벤져스 : 수상한 캠핑 대소동
7    8  극장판 포켓몬스터DP: 기라티나와 하늘의 꽃다발 쉐이미
8    9                          헤어질 결심
9   10                           룸 쉐어링
10  11                  니 부모 얼굴이 보고 싶다
11  12                          로스트 시티
12  13                              모어
13  14                             니얼굴
14  15                           애프터 양

In [10]:
# CSV로 저장하기
df.to_csv("../Data/DaumList.csv" , encoding="UTF-8", index = False)

In [11]:
# 저장한 CSV 파일 확인하기
pd.read_csv("../Data/DaumList.csv")

    순위                            영화제목
0    1                         탑건: 매버릭
1    2     마녀(魔女) Part2. The Other One
2    3                          범죄도시 2
3    4                             브로커
4    5                        버즈 라이트이어
5    6                    쥬라기 월드: 도미니언
6    7           극장판 윌벤져스 : 수상한 캠핑 대소동
7    8  극장판 포켓몬스터DP: 기라티나와 하늘의 꽃다발 쉐이미
8    9                          헤어질 결심
9   10                           룸 쉐어링
10  11                  니 부모 얼굴이 보고 싶다
11  12                          로스트 시티
12  13                              모어
13  14                             니얼굴
14  15                           애프터 양

In [13]:
# 동원오빠 코드
from bs4 import BeautifulSoup as bs
from urllib.request import urlopen
import pandas as pd

url = 'https://movie.daum.net/ranking/boxoffice/weekly'
html = urlopen(url)
soup = bs(html, 'html.parser')

# 데이터프레임 뼈대 만들기
df = pd.DataFrame(columns=['순위', '제목', '링크'])

movies = soup.select('div.box_boxoffice .link_txt')
for i, movie in enumerate(movies):
    df.loc[i] = [i+1, movie.text.strip(), movie['href']]

# 데이터프레임 csv로 저장하기
# df.to_csv('../Data/movie.csv', encoding='utf-8', index=False)

### 네이버 영화 순위
- https://movie.naver.com/movie/sdb/rank/rmovie.naver
- 탑건
- #old_content > table > tbody > tr:nth-child(2) > td.title > div > a

In [15]:
from bs4 import BeautifulSoup
from urllib.request import urlopen
import pandas as pd

url = "https://movie.naver.com/movie/sdb/rank/rmovie.naver"
page = urlopen(url)
soup = BeautifulSoup(page, "html.parser")

movies = soup.select(".tit3 > a ")

# 데이터프레임 뼈대 만들기
df = pd.DataFrame(columns=['Rank', 'Titles'])

for i, movie in enumerate(movies):
    df.loc[i] = [i+1, movie.text.strip()]

# 데이터프레임 csv로 저장하기
df.to_csv('../Data/naverRanking.csv', encoding='utf-8', index=False)

In [16]:
# 저장한 CSV 파일 확인하기
pd.read_csv("../Data/naverRanking.csv")

    Rank                          Titles
0      1                         탑건: 매버릭
1      2     마녀(魔女) Part2. The Other One
2      3                           범죄도시2
3      4                             브로커
4      5                        버즈 라이트이어
5      6                          헤어질 결심
6      7             닥터 스트레인지: 대혼돈의 멀티버스
7      8                    쥬라기 월드: 도미니언
8      9                     토르: 러브 앤 썬더
9     10                              실종
10    11                              탑건
11    12                          그대가 조국
12    13                             니얼굴
13    14                           룸 쉐어링
14    15                         외계+인 1부
15    16           극장판 윌벤져스 : 수상한 캠핑 대소동
16    17                          스파이더헤드
17    18                       한산: 용의 출현
18    19                           두개의 눈
19    20  극장판 포켓몬스터DP: 기라티나와 하늘의 꽃다발 쉐이미
20    21                              헌트
21    22                           디어 헌터
22    23                              모어
23    24                              마녀
24    25                           미친 능력
25    26                            비상선언
26    27                 더 킬러: 죽어도 되는 아이
27    28                           카시오페아
28    29                           미니언즈2
29    30                      극장판 주술회전 0
30    31                           경아의 딸
31    32                  니 부모 얼굴이 보고 싶다
32    33                           컴온 컴온
33    34                           리멤버 미
34    35                            아부쟁이
35    36                          개들의 도시
36    37                          센티그레이드
37    38                            더 렛지
38    39                         민스미트 작전
39    40                           감동주의보
40    41               신비한 동물들과 덤블도어의 비밀
41    42                     우스운게 딱! 좋아!
42    43                           고스트랜드
43    44                           어느 가족
44    45                           애프터 양
45    46                            이공삼칠
46    47                           뒤틀린 집
47    48                            클라우스
48    49                             엘비스
49    50                       윤시내가 사라졌다

---